// Defines the different views the application can be in.
export enum ViewType {
  NONE = 'none',
  CHAT = 'chat',
  IMAGE = 'image',
  VISIONARY = 'visionary',
  POETIC = 'poetic',
  CODE = 'code',
}

// Defines the role of a message sender.
export enum MessageRole {
  USER = 'user',
  AI = 'ai',
}

// Represents a single chat message.
export interface ChatMessage {
  id: string;
  role: MessageRole;
  content: string;
  isLoading?: boolean;
  uploadedImage?: {
    url: string; // data URL for preview
    mimeType: string;
  };
}

// Represents an image generated by the AI.
export interface GeneratedImage {
    id: string;
    prompt: string;
    imageUrl: string;
}

// Represents the data needed for the image editing modal.
export interface ImageForEditing extends GeneratedImage {
    base64: string;
    mimeType: string;
}
