// Defines the different views the application can be in.
export enum ViewType {
  NONE = 'none',
  CHAT = 'chat',
  IMAGE = 'image',
}

// Defines the role of a message sender.
export enum MessageRole {
  USER = 'user',
  AI = 'ai',
}

// Represents a single chat message.
export interface ChatMessage {
  id: string;
  role: MessageRole;
  content: string;
  isLoading?: boolean;
  imageUrl?: string;
}

// Represents an image generated by the AI.
export interface GeneratedImage {
    id: string;
    prompt: string;
    imageUrl: string;
}


// FIX: Removed puter.js global declaration as it's no longer used.
